//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplyInfo()
        {
            this.FullSpecialityInfoes = new HashSet<FullSpecialityInfo>();
        }
    
        public string ApplyInfoId { get; set; }
        public Nullable<int> FirstScore { get; set; }
        public Nullable<int> SecondScore { get; set; }
        public Nullable<int> ThirdScore { get; set; }
        public bool IsOrphan { get; set; }
        public bool IsGoH { get; set; }
        public bool IsWithoutExam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullSpecialityInfo> FullSpecialityInfoes { get; set; }
    }
}
